name: DevOps Assessment CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: |
          cd app
          npm install

      - name: Build Docker Image
        run: |
          cd app
          docker build -t devops-node-app .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform
          terraform init